config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  get 'post/show'
  get 'post/list'
  post 'post/question'
  get 'post/answer'

  devise_for :users

		root 'post#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/ask.rb
class Ask < ActiveRecord::Base
		belongs_to :user
		has_many :answers
		mount_uploader :ask_image, AskPhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		has_many :questions, class_name: 'Ask', foreign_key: 'to_id'
		has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

		def configure_permitted_parameters
				devise_parameter_sanitizer.for(:sign_up) << :name
				devise_parameter_sanitizer.for(:account_update) << :name
		end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
		before_action :authenticate_user! , only: [:index, :question, :answer]

		def index
				@user = current_user
				@ask = Ask.new
		end

		def show
				@user = User.find(params[:id])
				render 'index'
		end

		def list
				@users = User.all
		end

		def question
				Ask.create(user_id: current_user.id, to_id: params[:to], content: params[:ask], ask_image: params[:image_file])
				redirect_to :back
		end

		def answer
				if Ask.find(params[:ask_id]).to_id == current_user.id
				Answer.create(user_id: current_user.id, ask_id: params[:ask_id], content: params[:answer])
				end
				redirect_to :root
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LastAskFm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/index.html.erb
<h1><%= @user.name %>님의 페이지</h1>

<ol>
  <% @user.questions.each do |a| %>
    <%= a.user.name %> 님이 질문했습니다.</br>
    <%= a.content %></br>
    <img src="<%= a.ask_image_url %>">
    </br>
    <% if @user == current_user %>
      <form action = "/post/answer">
        <input type="hidden" name="ask_id" value="<%=a.id%>">
        <input type="text" name="answer">
        <input type="submit">
      </form>
    <% end %>

    <% a.answers.each do |u| %>
      <%= u.content %>
      </br></br>
    <% end %>
  <% end %>
</ol>

<%= form_tag '/post/question', multipart: true %>
<input type="hidden" name="to" value="<%=@user.id%>">
<input type="text" name="ask">
<input type="file" name="image_file">
<input type="submit">
</form>

<%= link_to 'Users', post_list_path %>
<%= link_to 'log out', destroy_user_session_path, :method => :delete %>

app/views/post/list.html.erb
<h>Users</h>

<p>
		<% @users.each do |u| %>
				<a href='/post/show?id=<%=u.id%>'><%= u.name %></a>
		<% end %>
</p>